# Generated by Django 4.2.6 on 2023-10-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='fonImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
