# Generated by Django 4.2.6 on 2024-01-13 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_color_shoes_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Color',
            new_name='Color1',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='color',
            new_name='color1',
        ),
        migrations.AddField(
            model_name='shoes',
            name='color2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.color2'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='color3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.color3'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='color4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.color4'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='color5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.color5'),
        ),
    ]
