# Generated by Django 4.2.6 on 2024-01-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_rename_color4_color_rename_color4_shoes_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.gender'),
        ),
    ]
