# Generated by Django 4.2.6 on 2024-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0011_quantity_shoes_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='quantity',
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.ManyToManyField(to='shoes.category'),
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
