# Generated by Django 4.2.6 on 2024-01-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0013_size39_size40_size41_size42_size43_size44_size45_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='size40',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size41',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size42',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size43',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size44',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size45',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size46',
        ),
        migrations.DeleteModel(
            name='Size40',
        ),
        migrations.DeleteModel(
            name='Size41',
        ),
        migrations.DeleteModel(
            name='Size42',
        ),
        migrations.DeleteModel(
            name='Size43',
        ),
        migrations.DeleteModel(
            name='Size44',
        ),
        migrations.DeleteModel(
            name='Size45',
        ),
        migrations.DeleteModel(
            name='Size46',
        ),
    ]
