# Generated by Django 4.2.6 on 2024-01-30 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0016_alter_size39_name_alter_size40_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='size39',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size40',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size41',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size42',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size43',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size44',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size45',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size46',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Size39',
        ),
        migrations.DeleteModel(
            name='Size40',
        ),
        migrations.DeleteModel(
            name='Size41',
        ),
        migrations.DeleteModel(
            name='Size42',
        ),
        migrations.DeleteModel(
            name='Size43',
        ),
        migrations.DeleteModel(
            name='Size44',
        ),
        migrations.DeleteModel(
            name='Size45',
        ),
        migrations.DeleteModel(
            name='Size46',
        ),
    ]
