# Generated by Django 4.2.6 on 2024-01-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0017_alter_shoes_size39_alter_shoes_size40_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='size39',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='size40',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size41',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size42',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size43',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size44',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size45',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size46',
        ),
    ]
