# Generated by Django 4.2.6 on 2024-01-31 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0019_size41_size42_size43_size44_size45_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='size',
            new_name='size41',
        ),
        migrations.AddField(
            model_name='shoes',
            name='size42',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.size42'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size43',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.size43'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size44',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.size44'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size45',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.size45'),
        ),
    ]
