# Generated by Django 4.2.6 on 2024-01-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0021_shoes_size39_shoes_size40_alter_shoes_size41_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='size39',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size40',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size41',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size42',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size43',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size44',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size45',
            field=models.CharField(max_length=255),
        ),
    ]
