# Generated by Django 4.2.6 on 2024-01-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0022_alter_shoes_size39_alter_shoes_size40_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='size41',
        ),
    ]
