# Generated by Django 4.2.6 on 2024-02-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0024_shoes_size41'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size39',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size40',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size41',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size42',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size43',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size44',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size45',
        ),
        migrations.AddField(
            model_name='shoes',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.quantity'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.size'),
        ),
    ]
