# Generated by Django 4.2.6 on 2024-02-02 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0025_quantity_size_remove_shoes_size39_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='quantity',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
