# Generated by Django 4.2.6 on 2024-02-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0027_remove_shoes_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shoes.color'),
        ),
    ]
