# Generated by Django 4.2.6 on 2024-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0028_shoes_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='fonImage',
            new_name='fonImage1',
        ),
        migrations.AddField(
            model_name='shoes',
            name='fonImage2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoes',
            name='fonImage3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoes',
            name='fonImage4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoes',
            name='fonImage5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoes',
            name='fonImage6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoes',
            name='fonImage7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
