# Generated by Django 4.2.6 on 2024-02-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0029_rename_fonimage_shoes_fonimage1_shoes_fonimage2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='fonImage6',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='fonImage7',
        ),
    ]
