# Generated by Django 4.2.6 on 2024-02-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0032_shoes_fonimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='fonImage',
        ),
    ]
